version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"  # Exposes NGINX on host port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - spring-nexus
    restart: unless-stopped
    
networks:
  spring-nexus:
    external: true