version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"  # HTTP port
      - "9300:9300"  # Internal transport port
    volumes:
      - esdata:/usr/share/elasticsearch/data  # Persist data across container restarts
    networks:
      - es_network
    restart: always  # Automatically restart if the container stops

volumes:
  esdata:

networks:
  es_network:
    driver: bridge
