# Yml for authentication service alone

version: '1.0'

services:
  elastic-service:
    image: elastic_service:${PROFILE}
    container_name: elastic_service
    build:
      context: .
      dockerfile: Dockerfile
      args: #This is passed inside Dockerfile
        PROFILE: ${PROFILE}
    ports:
      - "${ELASTIC_PORT}:8084"  # Host:Container
    environment:
      ELASTIC_REACTIVE_CLIENT_ENABLED: ${ELASTIC_REACTIVE_CLIENT_ENABLED}
      ELASTIC_CLUSTER_NODES: ${ELASTIC_CLUSTER_NODES}
      ELASTIC_CLUSTER_NAME: ${ELASTIC_CLUSTER_NAME}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_CONSUMER_GROUP_ID: ${KAFKA_CONSUMER_GROUP_ID}
      KAFKA_CONSUMER_TOPIC_NAME: ${KAFKA_CONSUMER_TOPIC_NAME}
      KAFKA_AUTO_OFFSET_RESET: ${KAFKA_AUTO_OFFSET_RESET}
      
    networks:
      - spring-nexus
    restart: no
  
networks:
  spring-nexus:
    external: true
# NEED EXTERNAL NETWORK docker network create spring-nexus
