# Yml for authentication service alone

version: '1.0'

services:
  database-service:
    image: database_service:${PROFILE}
    container_name: database-service
    build:
      context: .
      dockerfile: Dockerfile
      args: #This is passed inside Dockerfile
        PROFILE: ${PROFILE}
    ports:
      - "${DATABASE_SERVICE_PORT}:8081"  # Host:Container
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_TOPIC_NAME: ${KAFKA_TOPIC_NAME}
      # SQLite path inside container
      DATABASE_SQLITE_PATH: /volume/database_service.db
    volumes:
      - ${DATABASE_SQLITE_PATH}:/volume/database_service.db:rw
    networks:
      - spring-nexus
    restart: unless-stopped

networks:
  spring-nexus:
    external: true
# NEED EXTERNAL NETWORK docker network create spring-nexus