apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
  namespace: spring-nexus
  labels:
    app: auth-service
    tier: backend
spec:
  type: ClusterIP  # Internal cluster-only service
  selector:
    app: auth-service
  ports:
    - port: 8083           # Cluster-internal service port
      targetPort: 8083     # Port your container listens on
