apiVersion: v1
kind: Service
metadata:
  name: auth-service-nodeport
  namespace: spring-nexus
  labels:
    app: auth-service
    tier: backend
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - port: 8083           # Cluster-internal port
      targetPort: 8083     # Port your container listens on
      nodePort: 30083      # External NodePort (range: 30000-32767)
