apiVersion: v1
kind: Service
metadata:
  name: elastic-service-svc
  namespace: spring-nexus
spec:
  selector:
    app: elastic-service
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
  type: ClusterIP