---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: spring-nexus
  labels:
    app: kafka-zookeeper
spec:
  selector:
    app: kafka-zookeeper
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
  type: ClusterIP

  
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: spring-nexus
  labels:
    app: kafka-zookeeper
spec:
  selector:
    app: kafka-zookeeper
  ports:
    - name: zookeeper-port
      port: 2181
      targetPort: 2181
  type: ClusterIP
