apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
  namespace: spring-nexus
  labels:
    app: nginx
    tier: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf  # Only mount the nginx.conf file
      volumes:
        - name: nginx-config-volume
          persistentVolumeClaim:
            claimName: sqlite-pvc
