apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-svc
  namespace: spring-nexus
  labels:
    app: nginx
    tier: gateway
spec:
  # type: NodePort  # Expose it to host machine
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30080  # You can pick any port between 30000–32767
