apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: spring-nexus
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434
  type: ClusterIP  # Use NodePort or LoadBalancer if external access is needed
