apiVersion: v1
kind: Service
metadata:
  name: ollama-service-svc
  namespace: spring-nexus
  labels:
    app: ollama-service-app
    tier: backend
spec:
  # Change the type here:
  type: ClusterIP  # Use ClusterIP for internal access only
  # type: NodePort  # Uncomment this line to expose service externally via NodePort

  selector:
    app: ollama-service-app
  ports:
    - port: 8082
      targetPort: 8082
      # nodePort: 30082  # Specify this when using NodePort (optional; if not specified, Kubernetes assigns automatically)
