# pvc-sqlite.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
  namespace: spring-nexus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # MUST match PV
  resources:
    requests:
      storage: 1Gi
  volumeName: sqlite-pv  # bind to our specific PV
